"""Mandatory foreign keys

Revision ID: cd70cd573823
Revises: b85e40bca288
Create Date: 2019-01-25 10:30:33.186911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd70cd573823'
down_revision = 'b85e40bca288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shop', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_shop_location', table_name='shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shop_location', 'shop', ['location'], unique=False)
    op.alter_column('shop', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review', 'shop_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
