"""Adding timestamp for shops and reviews

Revision ID: f1759a0cd457
Revises: 867a8d96005a
Create Date: 2019-01-25 14:29:31.018302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1759a0cd457'
down_revision = '867a8d96005a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.add_column('shop', sa.Column('date_added', sa.DateTime(), nullable=True))
    op.drop_index('idx_shop_location', table_name='shop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_shop_location', 'shop', ['location'], unique=False)
    op.drop_column('shop', 'date_added')
    op.drop_column('review', 'date_added')
    # ### end Alembic commands ###
